#lang info
(define collection "straw")
(define deps '("base"))
(define build-deps '("scribble-lib" "racket-doc" "rackunit-lib" "gui-lib"))
(define scribblings '(("scribblings/straw.scrbl" ())))
(define pkg-desc "Description Here")
(define version "0.0")
(define pkg-authors '(hin))
(define license '(Apache-2.0 OR MIT))
(define gracket-launcher-names '("straw"))
(define gracket-launcher-libraries '("main.rkt"))
